name: "Release :: Publish"

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
        description: "Tag associated with the release"
      runners:
        type: string
        required: true
        description: "Jobs to run (JSON)"
        default: '{"serverless_logic_web_tools":"true"}'

env:
  KIE_TOOLS_REPO: ${{ vars.KIE_TOOLS_REPO || 'kubesmarts/kie-tools' }}
  SERVERLESS_LOGIC_SANDBOX_DEPLOYMENT_REPO: ${{ vars.SERVERLESS_LOGIC_SANDBOX_DEPLOYMENT_REPO || 'kiegroup/serverless-logic-sandbox-deployment' }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      upload_asset_url: ${{ fromJSON(steps.fetch_release_for_tag.outputs.data).upload_url }}
      release_ref: ${{ fromJSON(steps.fetch_release_for_tag.outputs.data).target_commitish }}
    steps:
      - name: "Fetch release for ${{ github.event.inputs.tag }}"
        uses: octokit/request-action@v2.1.0
        id: fetch_release_for_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: GET /repos/{repo}/releases/tags/{tag}
          repo: ${{ github.repository }}
          tag: ${{ github.event.inputs.tag }}

      - name: "Checkout kie-tools"
        uses: actions/checkout@v3
        with:
          path: kie-tools
          repository: ${{ env.KIE_TOOLS_REPO }}
          ref: ${{ fromJSON(steps.fetch_release_for_tag.outputs.data).target_commitish }}

      - name: "Check `tag` against `(package.json).version`"
        shell: bash
        run: |
          cd kie-tools
          [ "${{ github.event.inputs.tag }}" == "$(node -p "require('./package.json').version")" ]
          cd -

      - name: "Checkout serverless-logic-sandbox-deployment"
        uses: actions/checkout@v3
        with:
          path: serverless-logic-sandbox-deployment
          repository: ${{ env.SERVERLESS_LOGIC_SANDBOX_DEPLOYMENT_REPO }}

  build_and_publish:
    needs: [prepare]
    uses: ./.github/workflows/release_build.yml
    with:
      dry_run: false
      base_ref: ${{ needs.prepare.outputs.release_ref }}
      tag: ${{ github.event.inputs.tag }}
      upload_asset_url: ${{ needs.prepare.outputs.upload_asset_url }}
      runners: ${{ github.event.inputs.runners }}
    secrets:
      kie_group_tools_token: ${{ secrets.KIE_GROUP_TOOLS_TOKEN }}
      gh_token: ${{ secrets.GITHUB_TOKEN }}
