name: "Release :: Dry Run"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" # 6am UTC everyday
  pull_request:
    branches: ["**"]
    paths:
      - ".github/workflows/release*"
      - ".github/actions/**"

concurrency:
  group: ${{ github.event.pull_request && format('release-dry-run-pr-{0}', github.event.pull_request.number) || format('release-dry-run-ref-{0}', github.ref_name) }}
  cancel-in-progress: true

jobs:
  dry_run:
    if: github.repository == 'kiegroup/serverless-logic-sandbox-deployment'
    uses: ./.github/workflows/release_build.yml
    with:
      dry_run: true
      base_ref: ${{ github.event.pull_request && github.base_ref || github.ref }}
      runners: '{"serverless_logic_web_tools":"true"}'
